# Generated by Django 4.1.5 on 2024-01-05 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Genre', models.CharField(max_length=20)),
                ('Discription', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=20)),
                ('Release_date', models.DateField()),
                ('Duaration', models.DurationField()),
                ('Summary', models.CharField(max_length=200)),
                ('Movie_genre', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movapp.genre')),
            ],
        ),
    ]
