# Generated by Django 4.1.5 on 2024-01-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Duaration',
            field=models.CharField(max_length=20),
        ),
    ]
