# Generated by Django 4.1.5 on 2024-01-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movapp', '0002_alter_movie_duaration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Duaration',
            field=models.DurationField(max_length=20),
        ),
    ]
