# Generated by Django 4.1.5 on 2024-01-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movapp', '0003_alter_movie_duaration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Duaration',
            field=models.DurationField(),
        ),
    ]
