# Generated by Django 4.1.5 on 2024-01-06 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movapp', '0005_alter_movie_duaration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Movie_genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movapp.genre'),
        ),
    ]
